apiVersion: v1
kind: Service
metadata:
  name: {{ include "tritfabric-server.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "tritfabric-server.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
