apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tritfabric-vault
spec:
  provider:
    vault:
      server: "https://vault.REPLACE_ME:8200"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
